### ISSUE TITLE
Inconsistent triangle vertex ordering

### ISSUE THREAD

**Issue by manas-avi** [BrunoLevy/geogram#104]
Hi Bruno, 

In the connect_triangles function here at [https://github.com/BrunoLevy/geogram/blob/main/src/lib/geogram/voronoi/convex_cell.cpp#L1348](https://github.com/BrunoLevy/geogram/blob/main/src/lib/geogram/voronoi/convex_cell.cpp#L1348
)

The index ordering used in the two for loops: [1378:1380] and [1389:1391] seems to be inconsistent leading to unexpected assert failures. 

Best, 
Manas

**Comment by BrunoLevy** [comment]
Hi Manas,
They are not inconsistent: 
- [1378:1380] fills vv2t for a triangle t, and indicates that the three oriented edges (i,j), (j,k), (k,i) are adjacent to t
- [1389:1391] gets the three triangles connected to the three edges of triangle t, these three neighboring triangles are obtained from vv2t for the *inverted* edges (j,i),(k,j),(i,k)

Hope this helps,
Best,
--Bruno
