### ISSUE TITLE
How to use delaunay using tetgen

### ISSUE THREAD

**Issue by tyc1998** [BrunoLevy/geogram#12]
Sorry to bother again.
The same method got the correct result in BDEL, but got the wrong result in tetgen, don't know if it's a problem with my use.

Code is just like this
```
  GEO::initialize();
  GEO::CmdLine::import_arg_group("standard");
  GEO::CmdLine::import_arg_group("pre");
  GEO::CmdLine::import_arg_group("algo");
  
  GEO::Delaunay::initialize();
  GEO::Delaunay_var T = GEO::Delaunay::create(3, "tetgen");//or use "BDEL"

  T->set_vertices(vertex.size() / 3, vertex.data());//vertex is the points
  //Then use T->cell_to_v() to get information of tets
```
Another problem is that I can't find a method for tetrahedral division of the point set using constraint delaunay. Can you give a demo easily?

**Comment by tyc1998** [comment]
Thanks for your answer.
In fact my difficulty lies in reconstructing the GEO::mesh in favor of the geometry I already have. The information I have now is the constraint points and the constraint triangles. I think adding the vertex, edge and facet information from the mesh is enough, but it looks like this is missing the facet_cornor information

**Comment by BrunoLevy** [comment]
use `mesh.vertices.create_vertex()` and `mesh_facets.create_triangle()`, and when all the facets are created, call `mesh.facets.connect()`.

**Comment by tyc1998** [comment]
I coded as you gave, but the result is not what I expected.
Geogram told me as follows.
```
o-[DelaunayTetg] Warning: Constraints have 4148 edge(s) on the border
o-[Delaunay    ] Warning: Only 0 vertices, may be not enough
```

My pseudo code is as follows.
```
		GEO::Mesh constrains;
		for (int v : constrian_vertex)
			constrains.vertices.create_vertex(tet_vertex_[v].pos_.data());
		assert(constrains.vertices.nb() == constrian_vertex.size());
		for (auto& tri : constrian_face)
			constrains.facets.create_triangle(vertex_map[tri[0]], vertex_map[tri[1]], vertex_map[tri[2]]);
		assert(constrains.facets.nb() == constrian_face.size());
		constrains.facets.connect();
		constrains.assert_is_valid();

		GEO::Delaunay::initialize();
		GEO::Delaunay_var T = GEO::Delaunay::create(3, "tetgen");

                T->set_reorder(false);
		T->set_constraints(&constrains);

                const int n_pts = vertex.size() / 3;
		T->set_vertices(n_pts, vertex.data());
```
The assertion is not fired, yet the geoogram tells me that there is no vertex in it, which confuses me.
It's worth mentioning that my case is not the same as the one in mesh_tetrahedralize.cpp, the constraint boundary in my constraints is not closed, but according to my understanding of the constraint delaunay algorithm, this should be irrelevant.

**Comment by BrunoLevy** [comment]
- It is not clear to me what you are trying to achieve (especially when you say "my constraints is not closed" ). Would you post an image of your constraints and a description of what you expect from the result ? 

- I'd also suggest to do the following steps: 
   - write your constraint in a file, using `mesh_save()` from `<geogram/mesh/mesh_io.h>`:
     `mesh_save(constrains,"constrains.meshb")`
   - inspect it with `vorpaview`
   - use 'vorpalite profile=tet constraint.meshb

**Comment by tyc1998** [comment]
I can describe what I want to do. My input is some set of points as well as some triangles and I want to get a set of tetrahedra containing the original triangles. Note that these triangles are not used to describe the geometry boundary information as in the stl file, but simply the shape of the set that I want to keep.
![image](https://user-images.githubusercontent.com/31647878/180606445-52e603d2-0c2b-4094-adc2-cfa374ef1d4a.png)
![image](https://user-images.githubusercontent.com/31647878/180606468-3a9fdc72-8490-4645-bebb-bf885ad8be26.png)
Note that the tetrahedron on the left and the tetrahedron on the right in the first picture are not a whole. I want to use the constraints of part of the surface of the left mesh and part of the surface of the right mesh to re-mesh the middle part to get a common The overall mesh of nodes. Of course, after the re-division I would like to mesh it optimally.
It's a bit difficult to describe, especially since English is not my native language, don't know if you can understand what I mean

**Comment by BrunoLevy** [comment]
I think I mostly understand what you want to do. If I got it right:
- first image is your whole geometry
- second image is what you want to keep

Here is what I recommend
-1) load a volumetric mesh that corresponds to the first image, with all the tets
-2) remove all the tets that you want to keep (sounds stupid in the first place, but wait !)
   you can use [`mesh.cells.delete_elements()`](https://brunolevy.github.io/geogram/classGEO_1_1MeshElements.html#a20e3a80385aad58bca831dd15e7da2e7)
-3) compute the boundary of the remaining tets
   you can use [`mesh.cells.compute_borders()`](https://brunolevy.github.io/geogram/classGEO_1_1MeshCells.html#a1dfb5bc37971adcf2636620c01fb65c7)
-4) remove the tetrahedra
   you can use `mesh.cells.clear(); mesh.vertices.remove_isolated();`
-5) now you have a closed surface that represents the domain you want to remesh (and you have no choice, that is what you need, the algorithm cannot "guess it" from "what you want to keep"). Use the closed surface as a constraint for tetgen (as we have seen before)
-6) merge the so-obtained mesh with "what you want to keep". Note that vertices will be duplicated on the common boundaries, to merge them, use 
  [mesh_repair()](https://brunolevy.github.io/geogram/mesh__repair_8h.html)

Now maybe you wanted to remesh the surfacic part from your image 1 that does not touch your image 2. If you want to do that, then start by computing the surfacic border of image 1, and eliminate from it all the triangles that exist in image 2. Then remesh what remains, and glue it with what you wanted to keep (it is the "surfacic version" of what's explained above).

Hope this helps !

**Comment by tyc1998** [comment]
I coded as you did, however the geoogram tells me that my input faces intersect.
My approach is to rebuild the constraint information myself using `mesh.vertices.create_vertex()` and `mesh.cells.create_tet()`.
I think the reason may be due to the fact that the mesh in my left part and in the right part are not a whole, they do not share vertices on the boundary.
Another problem is that since I did not strictly adhere to the boundary information when mesh the left part and the right part, the meshes of the two parts may overlap, and even the two parts may have holes on the boundary. In this case, I prefer to use `mesh.vertices.create_vertex()` and `mesh.facets.create_triangle()` to create constraint information. This constraint information only contains the interface facets of the mesh I want to keep and the mesh I want to remove. I've tried this way but it failed with no tets gengerate. I don't know if the algorithm is not supported or I am using it wrong.

**Comment by BrunoLevy** [comment]
Would you save the constraints in a file and send it to me so that I can take a look ? (use mesh_save() in geogram/mesh/mesh_io.h).

**Comment by tyc1998** [comment]
[T.zip](https://github.com/BrunoLevy/geogram/files/9176042/T.zip)
Thanks again for your reply!
1. The geoogram is generated based on the faces I selected myself. The result of constructing a tetrahedron based on this file and adding extra vertices is empty.
2. The geogram is the constraint I generated according to your method, and the geogram indicates that the constraint surface has intersecting surfaces.

**Comment by tyc1998** [comment]
I checked 2.geogram again, I compared this file with the boundary information I need in hypermesh, I don't think there is any problem. But mesh with constrains alwyas falied, which toubled me.  >_<

**Comment by BrunoLevy** [comment]
Inspect your meshes (for instance with GraphiteThree here: https://github.com/BrunoLevy/GraphiteThree)

Inside your mesh, there is a "wall" that separates the two halves, and this wall exists in both halves with a different triangulation
(the following image uses a "clipping plane" to reveal the internal structure of your mesh)
![image](https://user-images.githubusercontent.com/19478253/181346588-4d8089e8-874e-4c4c-bfd4-c508ccc31683.png)

If you look at it from the bottom, you see the non-conformal triangles meeting on the wall:
![image](https://user-images.githubusercontent.com/19478253/181346605-63b47afc-ef79-4ff2-8ec3-eb267df1b223.png)

Without fixing this, you got no chance !

**Comment by tyc1998** [comment]
I know that's a bug, in other words, the problem is exactly what I'm trying to solve.
Can I use the constraint surface I found myself to constrain it, as shown in the figure below.
I found out that no new cells were generated when I was using it (the extra vertices I added in the middle of the constraints).
![image](https://user-images.githubusercontent.com/31647878/181406725-e9dc315d-bad9-4bba-ba65-7f310984cc52.png)

**Comment by BrunoLevy** [comment]
If you want to use Tetgen, you first need to create a *clean* *closed* surface that represents the region you want to fill with tetrahedra.
In your configuration, you first need to
   - remove the duplicated surface inside (circled zone on top figure in my previous post)
   - remesh the surface in a consistent way for both halves (bottom figure in my previous post)
There is no standard algorithm for that...
... but your geometry is pretty simple, why not starting from a nice closed mesh of the whole shape in the first place ?

**Comment by tyc1998** [comment]
This is just a demo, I'm doing research on dealing with complex geometries. It seems that it is not feasible to use tetgen for constrained delauny segmentation, do you have any other library recommendations for this situation?

**Comment by BrunoLevy** [comment]
It's because what you need is *not* a constrained Delaunay tetrahedralization (because *by definition* constrained Delaunay tetrahedralization needs a clean, closed boundary in the first place). What you need first is a *surface mesh repair* utility. There are commercial tools that may have it (MeshGems). You can try also MeshFix (https://github.com/fangq/meshfix). There is also TetWild (https://github.com/Yixin-Hu/TetWild) that may work with non-comforming triangles (my figure 2) but you will need to remove the duplicated wall in the first place.

**Comment by tyc1998** [comment]
OK, thanks a lot!

**Comment by tyc1998** [comment]
I‘ve just repaired intersection of constrains. But GEO::Delaunay with tetgen errors like before, by providing information "Error: Encountered a problem, relaunching in diagnose mode" and "Error: Found 0 facets with intersections.", which confused me. In my opinion. no faces intersections should not be problem. 
The repaired constrian boundaries is as follows.
[cb.zip](https://github.com/BrunoLevy/geogram/files/9536356/cb.zip)
Sorry to bother agian, and look forward to your help.

**Comment by tyc1998** [comment]
It seems that stl file contains some errors. I'll check it.

**Comment by BrunoLevy** [comment]
I just tested, your file is mostly fine, but it has non-manifold edges. 
1) download and install [graphite][https://github.com/BrunoLevy/GraphiteThree)
2) Load your file in Graphite
3) Surface->Repair->Merge vertices
4) Volume->Tet meshing (uncheck "preprocess")
Note: your mesh has non-manifold edges, which is why it fails with the default arguments
Refer to the source-code of Graphite to see how to call the corresponding geogram functions:
- [mesh_grob_surface_commands.cpp](https://github.com/BrunoLevy/GraphiteThree/blob/main/src/lib/OGF/mesh/commands/mesh_grob_surface_commands.cpp), line 98
- [mesh_grob_volume_commands.cpp](https://github.com/BrunoLevy/GraphiteThree/blob/main/src/lib/OGF/mesh/commands/mesh_grob_volume_commands.cpp), line 184
