### ISSUE TITLE
How to compile for Android?

### ISSUE THREAD

**Issue by ThibautRousselet** [BrunoLevy/geogram#13]
Hello,

I was wondering if there was a way to compile this library for Android?
I have managed to generate a visual studio solution for Android with cmake for now but I have not been successful in building it.

Thank you!

**Comment by BrunoLevy** [comment]
Hello, 
- In the past it was possible to compile all Geogram applications as Android programs using the NDK. Unfortunately now the CMake version bundled in the NDK has an incompatibility with the CMakefiles used to compile geogram and it no longer works. I plan to fix that when I have time (but did not have the time up to now). 
- I am now refering to ImGui as a git submodule. In the past it was a "fork" with a couple of adjustment for Android. When the CMake / NDK build tools issue is fixed, we will have also to tinker a bit to make it work again.

**Comment by BrunoLevy** [comment]
Restored Android support in latest version (1.8.5-rc). See instructions [here](https://github.com/BrunoLevy/geogram.android#geogramandroid)
