### ISSUE TITLE
How to build for iOS?

### ISSUE THREAD

**Issue by EShi538** [BrunoLevy/geogram#15]
Is it possible to build this for iOS?

**Comment by BrunoLevy** [comment]
Hi,
I never tried to compile geogram on iOS,
The only non-portable part is geogram_gfx, that uses OpenGL (which I think is not supported on IOS),
so you may need to create a `CMakeOptions.txt` file with `set(GEOGRAM_WITH_GRAPHICS OFF)`,
see `geogram/CMakeOptions.txt.sample` for an example.
You may also need to create a new `cmake/platforms/ios.cmake` file and specify some options there.

**Comment by EShi538** [comment]
Thanks
