### ISSUE TITLE
Build is broken with clang-19: no member named 'm_N' in 'SparseMatrix<T>'

### ISSUE THREAD

**Issue by yurivict** [BrunoLevy/geogram#188]
Clang-19 is more rigorous and is now finding missing class fields in uninstantiated and unused functions:
```
In file included from /wrkdirs/usr/ports/math/geogram/work/geogram-1.9.0/src/lib/geogram/third_party/PoissonRecon/poisson_geogram.cpp:61:
In file included from /wrkdirs/usr/ports/math/geogram/work/geogram-1.9.0/src/lib/geogram/third_party/PoissonRecon/SparseMatrix.h:191:
/wrkdirs/usr/ports/math/geogram/work/geogram-1.9.0/src/lib/geogram/third_party/PoissonRecon/SparseMatrix.inl:197:22: error: no member named 'm_N' in 'SparseMatrix<T>'
  197 |         Resize(this->m_N, this->m_M);
      |                ~~~~  ^
/wrkdirs/usr/ports/math/geogram/work/geogram-1.9.0/src/lib/geogram/third_party/PoissonRecon/SparseMatrix.inl:197:33: error: no member named 'm_M' in 'SparseMatrix<T>'
  197 |         Resize(this->m_N, this->m_M);
      |                           ~~~~  ^
```

[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p380be9c7980a_s5036d9652a5/logs/geogram-1.9.0.log)

**Comment by BrunoLevy** [comment]
Hello, did you have the opportunity to check again ? Does it compile now with clang-19 ?
(just to know whether I can close this issue and create the new release)
Thank you in advance.

**Comment by thierry-FreeBSD** [comment]
I can confirm that with [d986771](https://github.com/BrunoLevy/geogram/commit/d986771ed46a334764844b244e633ac7c15b40e7), together with https://github.com/BrunoLevy/geogram/commit/2e1b6fba499ddc55b2150a1f610cf9f8d4934c39 compilation is fixed on FreeBSD using clang-19.
