### ISSUE TITLE
Clarification on compute_RVC() documentation

### ISSUE THREAD

**Issue by akrodger** [BrunoLevy/geogram#25]
I'm confused about the wording on the documentation of the 4th input parameter of compute_RVC() within the RestrictedVoronoiDiagram class. It reads as

> [in]	copy_symbolic_info	if true, symbolic information is copied. An attribute "id" is attached to the facets. The value of id[f] is either 1 + the index of the Voronoi vertex that generated with i the bisector that created the facet, or -1-g if the facet was an original facet of mesh M, where g is the index of the original facet in M.

It says "Voronoi vertex" but then mentions the bisecting plane. However, don't the vertices of the Delaunay graph generate the bisecting planes? Does this actually refer to the generating seed point for a voronoi cell or a vert of the voronoi graph? Or perhaps I am misunderstanding something else. Thanks for any clarification.

**Comment by BrunoLevy** [comment]
Yes, the documentation is not clear, "Voronoi vertex" means "generating seed point of Voronoi cell". 
- if id[f] is positive, then the facet is on the bisecting plane of the current vertex and vertex id[f]-1
- if id[f] is negative, then the facet is a part of a facet of M, and -1-id[f] is the index of the facet in mesh M

**Comment by akrodger** [comment]
Excellent, thank you again!
