### ISSUE TITLE
Repository tags

### ISSUE THREAD

**Issue by nursik** [BrunoLevy/geogram#27]
Hello, I would like to know, if tags are going to be introduced in this repository. As some [comments](https://github.com/BrunoLevy/geogram/issues/11#issuecomment-1246596027) show, users want to have tags to distinguish different versions. Also, it will be handy to see actual releases rather than intermediate ongoing work.

**Comment by BrunoLevy** [comment]
Yep, I'll try to do that, several users asked for it (just need to figure out how this works !). I have a couple of fixes to push before then. Hopefully it will be for next week if everything goes well...

**Comment by BrunoLevy** [comment]
Pushed tag v1.8.1

**Comment by BrunoLevy** [comment]
Release v1.8.2 will be there in a couple of days (with non-regression tests and a couple of fixes that several people need).
