### ISSUE TITLE
In what situation will CDT failed

### ISSUE THREAD

**Issue by tyc1998** [BrunoLevy/geogram#30]
I provide a mesh as consatrains for tetgen delaunay, while in this situation delaunay 3D will failed with providing "Warning: Only 0 vertices, may be not enough". I has checked the constrains with assert_is_valid(), and assert is not triggered.
The constraint mesh is as follows.
Best wishes!
[2.zip](https://github.com/BrunoLevy/geogram/files/9934592/2.zip)

**Comment by BrunoLevy** [comment]
- load your mesh in [Graphite](https://github.com/BrunoLevy/GraphiteThree)
- surface->repair->merge vertices
- visualize border: 
![image](https://user-images.githubusercontent.com/19478253/200307015-152fb1c9-c5b8-4312-a858-bdc91418da3c.png)
![image](https://user-images.githubusercontent.com/19478253/200307016-cfa1a0ea-19d8-4375-ae4a-fc5bf57409e4.png)

-> your mesh is not closed, cannot tetrahedralize it !

In particular, this zone:
![image](https://user-images.githubusercontent.com/19478253/200307289-9c3d4b0e-aa33-45d0-9bdf-e05a1ab7e00f.png)
