### ISSUE TITLE
Version string shouldn't have "-rc" if using the release

### ISSUE THREAD

**Issue by dkogan** [BrunoLevy/geogram#33]
Hi. I'm packaging the new 1.8.1 release, and I'm having to apply this patch: https://salsa.debian.org/science-team/geogram/-/blob/master/debian/patches/no-rc-version.patch

The version is "1.8.1" not "1.8.1-rc". Would you like to merge the patch?

Thanks!

**Comment by BrunoLevy** [comment]
I think it is difficult to modify an existing release, but I'm releasing 1.8.2 in a couple of days (with fixed licensing information, c.f. you other issue, and a couple of other changes)
