### ISSUE TITLE
Licensing: can we remove all the requirements to provide notice of modifications?

### ISSUE THREAD

**Issue by dkogan** [BrunoLevy/geogram#34]
Hi. I'm looking at packaging the new 1.8.1 release. It looks like you simplified many of the licenses; thanks for doing that! But many files still contain requirements to provide notice of modifications. For instance here:

https://github.com/BrunoLevy/geogram/blob/3b857461730d842696be63afb0d9b169bfe6092c/src/lib/exploragram/hexdom/geometry.cpp#L19

Can we remove those extra clauses? The ones applying to GPL licenses (such as the above link) are particularly problematic. The GPL explicitly says that such additional restrictions are not allowed and any license that is GPL + extra such restrictions can be treated as just "GPL":

```All other non-permissive additional terms are considered “further restrictions” within the meaning of section 10. If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.```

Can you release 1.8.2 with this license update?

Thanks

**Comment by BrunoLevy** [comment]
Ooops, I overlooked a couple of files, I'm fixing that...

**Comment by BrunoLevy** [comment]
Fixed in the latest commit (and double checked with a recursive grep).

**Comment by BrunoLevy** [comment]
Would you take a look at the current version ? If there are small changes to make, I'd rather include them in 1.8.2 (not possible to change once released). Thank you in advance.

**Comment by dkogan** [comment]
I just looked at the current git. I see this:

```
dima@shorty:~/projects/geogram$ git grep -li 'If you modify this software, you should include a notice'

doc/devkit/PSM.dox
doc/devkit/design.dox
doc/devkit/license.dox
doc/devkit/mainpage.dox
doc/devkit/programmer.dox
```

**Comment by dkogan** [comment]
While I'm at it, here are some other licensing inconsistencies (everything found by grepping the sources for "copyright"):

- The BSD-3clause text in the LICENSE file isn't identical to the license text in most of the sources. They aren't different in any important way, but looking and finding the differences can waste people's time. Can we remove the LICENSE file? It doesn't apply to ALL the sources anyway.
- src/lib/geogram/basic/command_line.cpp prints out a copyright statement. It doesn't have matching copyright years. Can that printing be removed?

That's it, I think. Thanks for looking at this!

**Comment by BrunoLevy** [comment]
Fixed.
Normally v1.8.2 will be created this WE, please tell me if you find something else before then.
Best,
-- B

**Comment by BrunoLevy** [comment]
1.8.2 is out !
