### ISSUE TITLE
size adaptation

### ISSUE THREAD

**Issue by xiaolong7** [BrunoLevy/geogram#35]
Hello, I tried the size adaption (from 0 to 1) of the remeshing algorithm while setting the anisotropy parameter as 0. When the size adaptation approaches 1, the resulting mesh has some strange dense distribution of triangles in some region, highlighted by the red circle in the below screenshot. The background color indicates the surface curvature. The  curvature in the highlighted region is similar to the surrounding in the horizontal direction but has very dense mesh distribution. Do you have any idea why this happened or suggestions about how to mitigate it? Thank you!

![image](https://user-images.githubusercontent.com/104316304/200396000-db7dfb96-0bc5-4f41-966f-b0d137de43f2.png)

**Comment by BrunoLevy** [comment]
Hi, would you share your input mesh ?

**Comment by xiaolong7** [comment]
> Hi, would you share your input mesh ?

Here it is. Thank you for looking into it. I have tried setting the target number of points after remeshing as 2600 or 5000 with `tri_size_adapt=1`, `tri_shape_adapt=0`, and default values for other parameters. Both gave something similar o that shown in the above figure in some region close to the boundary.
[test.zip](https://github.com/BrunoLevy/geogram/files/9975339/test.zip)

**Comment by xiaolong7** [comment]
Hi, if I understand it correctly, the size adaptation in the remehshing algorithm right now considers the curvature of the surface. Is it possible for the size adaptation to also consider the curvature of surface boundary (non-closed surface), such as the below example of a surface mesh? 
![image](https://user-images.githubusercontent.com/104316304/201236149-ad2d8992-2750-405c-9318-887aecf013cb.png)

**Comment by BrunoLevy** [comment]
Pushed a "quick an dirty fix":
![image](https://user-images.githubusercontent.com/19478253/201388003-02f2d021-2755-407c-a45e-33458981e99b.png)
(will not solve the problem in all cases though).
The problem comes from the way I am estimating Local Feature Size, uzing poles (a subset of Voronoi vertices), and sometimes one of the poles is very near the surface, making the mesh much denser around this spurious pole.
For now I have just limited the magnitude of the sizing field. 
This will require deeper investigations ...

**Comment by BrunoLevy** [comment]
Regarding the second question (sizing field adapted to the border), you can use remesh_smooth() with your own sizing field,
for instance, something like what's described in [this article](https://link.springer.com/chapter/10.1007/978-3-540-75103-8_19)

**Comment by xiaolong7** [comment]
> Pushed a "quick an dirty fix": ![image](https://user-images.githubusercontent.com/19478253/201388003-02f2d021-2755-407c-a45e-33458981e99b.png) (will not solve the problem in all cases though). The problem comes from the way I am estimating Local Feature Size, uzing poles (a subset of Voronoi vertices), and sometimes one of the poles is very near the surface, making the mesh much denser around this spurious pole. For now I have just limited the magnitude of the sizing field. This will require deeper investigations ...

Thank you for looking into it and your suggestion!
