### ISSUE TITLE
Windows compilation 

### ISSUE THREAD

**Issue by hbadi** [BrunoLevy/geogram#36]
Hello,

Does Geogram can be compiled with Visual Studio ? Is there window binary asset ?
I tried to configure with cmake but i got an error cause glfw folder is empty

Thanks for your help

**Comment by BrunoLevy** [comment]
I realized that the package generated by github when creating a release do not include submodules...
Use the procedure detailed [here](https://github.com/BrunoLevy/geogram/wiki/compiling_Windows) instead.

Best regards,
-- Bruno

**Comment by hbadi** [comment]
Thank you Bruno, that's works now !
I can find where are some stl input mesh files (like the motor mesh used for tetmesh) ?

Best regards.
