### ISSUE TITLE
LM7 license

### ISSUE THREAD

**Issue by starseeker** [BrunoLevy/geogram#48]
Hi!  Looking at the 3rd party code, I notice that the LM7 copy included with geogram is LGPL, even though the newest upstream code is MIT licensed.  Does geogram need the older version, or could it be upgraded to the MIT version?

**Comment by BrunoLevy** [comment]
Normally nothing prevents from upgrading to the upstream version. 
I'll probably include it as a submodule in the next release.

**Comment by BrunoLevy** [comment]
Pushed version with libMeshb as submodule. Non-regression tests are running ...

**Comment by BrunoLevy** [comment]
Tests passed (one of the jobs marked as failed, but it is just a problem of concurrency with other jobs when publishing the results, need to fix that...)
