### ISSUE TITLE
Windows build: sccache deactivated

### ISSUE THREAD

**Issue by BrunoLevy** [BrunoLevy/geogram#5]
In the "Prepare sccache" step it says:
```
Initializing...
Invoke-Expression: D:\a\_temp\ff2ee3ee-f101-4b64-b0b3-df1f0e660f49.ps1:2
Line |
   2 |  Invoke-Expression (New-Object System.Net.WebClient).DownloadString('h …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Select-CurrentVersion' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Error: Process completed with exit code 1.
```
Do you have any hint @jdumas ?
(note: I've added yesterday github actions to build Doxygen doc and publish it on gh-pages, but I think it is unrelated)

**Comment by jdumas** [comment]
Seems to be an issue with the [scoop installer](https://github.com/ScoopInstaller/Scoop/issues/4783). It should be fixed soon!

**Comment by BrunoLevy** [comment]
Thank you Jeremie !

**Comment by BrunoLevy** [comment]
Leaving the issue open as a reminder that sccache should be reactivated as soon as scoop installer issues is fixed (https://github.com/ScoopInstaller/Scoop/issues/4783)

**Comment by BrunoLevy** [comment]
Re-activated sccache, works again.

**Comment by BrunoLevy** [comment]
with latest update of scoop, it fails again (not running as admin by default anymore, and needed for sccache it seems).
For now, I deactivated sccache again in Build action so that Windows compile works.

**Comment by jdumas** [comment]
Argh!
Maybe you can use the same changes as [this guy](https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1673/files)?

**Comment by BrunoLevy** [comment]
For now, deactivating cache build (does not gain a lot and makes build system much more complicated...)
