### ISSUE TITLE
Incorrect info in file header comments

### ISSUE THREAD

**Issue by starseeker** [BrunoLevy/geogram#51]
Looks like the following files have obsolete info:

tests/lib/VorpatestLibrary.py
tools/testenv.sh.in
tools/testenv.bat.in

**Comment by BrunoLevy** [comment]
Which obsolete info ? 
They are still used by non-regression tests (more info [here](https://github.com/BrunoLevy/geogram/wiki/DevOps#tests))

**Comment by starseeker** [comment]
They're labeled "Confidential" and "proprietary"

**Comment by BrunoLevy** [comment]
Ah yes, will fix that...

**Comment by BrunoLevy** [comment]
Fixed.
