### ISSUE TITLE
Vorpaline?

### ISSUE THREAD

**Issue by starseeker** [BrunoLevy/geogram#52]
Looking over the build system, there are quite a number of references to variables using the VORPALINE_  convention...  Does GEOGRAM need to retain the ability to build as either project(Vorpaline) or project(Geogram)?

If not, would pull requests removing the VORPALINE variable name/conditionals be of interest?

**Comment by BrunoLevy** [comment]
Yes, Vorpaline still exists, and is marketed by [Tessael](https://www.tessael.com/)
