### ISSUE TITLE
Question about Co3Ne and mesh repair

### ISSUE THREAD

**Issue by starseeker** [BrunoLevy/geogram#53]
I doubt that this is an issue - more of a question/confirmation request about what the expected capabilities and limitations are of the geogram algorithms.

One of our CAD system's fallback facetization routines for implicit boolean geometry is to shoot rays, generate a point cloud, and then do surface reconstruction.  Usually we use PoissonRecon, but that fails fairly miserably for super thin, large surface area solids.  I tried such an example with geogram's Co3Ne and got very interesting results (see images below).  However, the mesh doesn't appear to be (quite) fully manifold and surface repair seems to be unable to completely resolve the issues.  Is this normal/expected for this type of input data set?

![image](https://user-images.githubusercontent.com/238416/205354048-3d826b03-e804-4355-9bd8-157918fc2080.png)

![image](https://user-images.githubusercontent.com/238416/205354213-cf59d57a-f810-446f-bb27-5311838625c8.png)

**Comment by BrunoLevy** [comment]
Difficult for me to see, is it a surface, or is it a very thin volume with a closed boundary ?
If it is a very thin volume with a closed boundary, for Poisson reconstruction, make sure you generate *normals* with the points. Make sure also that you use a sufficiently large *depth* to capture the thickness of the surface.

**Comment by starseeker** [comment]
The original source of the point cloud is two very thin volumes with closed boundary defined by implicit primitive booleans.  I need to dig more deeply into the algorithms to ask more intelligent questions, so I'll go ahead and close this out - thanks!
