### ISSUE TITLE
Help compiling with gargantua?

### ISSUE THREAD

**Issue by akrodger** [BrunoLevy/geogram#55]
_Bruno: problem now fixed. Still need to add non-regression tests in GARGANTUA mode to avoid this type of issue in the future_

Hi, thanks for your time addressing my question.
I am trying to compile with gargantua, but I am having a build failure. I am on redhat linux 64 bit. I have no problems compiling without gargantua. Here are my steps.

`cp CMakeOptions.txt.gargantua CMakeOptions.txt`
`sh ./configure.sh Linux64-gcc-dynamic`
`cd ./build/Linux64-gcc-dynamic-Release/`
`make -j 1`

The build reaches 76% and fails with the last statement being
`[ 76%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/NL/nl_amgcl.cpp.o`
Followed by many GCC errors complaining about conflicting types. For example:

`In file included from geogram/src/lib/geogram/NL/nl.h:1455,`
`                 from geogram/src/lib/geogram/NL/nl_amgcl.h:43,`
`                 from geogram/src/lib/geogram/NL/nl_amgcl.cpp:6:`
`geogram/src/lib/geogram/NL/nl_64.h:59:15: error: conflicting declaration of C function ‘double nlGetVariable(NLulong)’`
`   59 | inline double nlGetVariable(NLulong i) {`
`      |               ^~~~~~~~~~~~~`
`In file included from geogram/src/lib/geogram/NL/nl_amgcl.h:43,`
`                 from geogram/src/lib/geogram/NL/nl_amgcl.cpp:6:`
`geogram/src/lib/geogram/NL/nl.h:1006:31: note: previous declaration ‘NLdouble nlGetVariable(NLuint)’`
` 1006 |     NLAPI NLdouble NLAPIENTRY nlGetVariable(NLuint i); `

**Comment by BrunoLevy** [comment]
I'll take a look at that. I added amgcl interop recently, and I probably overlooked something. Will keep you update shortly.

**Comment by akrodger** [comment]
If this helps you at all, I had no problems when compiling and using Gargantua mode on the following commit:
abc3a5d4c4ce7772b0ad03180cda8ae910bb66c4
Thanks again for your time and dedication.

**Comment by BrunoLevy** [comment]
I pushed a fix. 
Did not add non-regression tests in GARGANTUA mode yet (so please tell me whether it works for you).

**Comment by akrodger** [comment]
Thanks, I was able to compile with that commit. I did get sign conversion warnings in mesh_io though. Here is an example.

`geogram/src/lib/geogram/mesh/mesh_io.cpp:936:67: warning: conversion to ‘int64_t’ {aka ‘long int’} from ‘GEO::index_t’ {aka ‘long unsigned int’} may change the sign of the result [-Wsign-conversion]`
`  936 |             GmfSetKwd(mesh_file_handle, GmfVertices, M.vertices.nb());`
`      |                                                      ~~~~~~~~~~~~~^~`

It is not clear to me that these are actually bad, but I figured out I would report everything about trying the commit back to you.

**Comment by BrunoLevy** [comment]
Thanks !
This one is a-priori not problematic (and I fixed it in the latest commit)

**Comment by BrunoLevy** [comment]
(still need to add non-regression tests in GARGANTUA mode so I re-opened the issue)

**Comment by BrunoLevy** [comment]
TODO  list
 - [x] fix GARGANTUA mode in `nl_amgcl.cpp`
 - [x] add  GARGANTUA configuration in smoke tests 
 - [x] fix GARGANTUA compilation under Windows and MacOS
 - [ ] fix warnings 
 - [ ] distinguish tests that can run under GARGANTUA and tests that can't
 - [ ] add GARGANTUA configuration in night tests

**Comment by BrunoLevy** [comment]
Let's wait for night test results before closing the issue... (it may start tests of features that are unsupported in Gargantua mode).

**Comment by BrunoLevy** [comment]
night tests ok
