### ISSUE TITLE
Does geogram support power diagram？

### ISSUE THREAD

**Issue by xiaowuga** [BrunoLevy/geogram#62]
Hi, thanks for offer such excellent algorithm library?
Does geogram support power diagram？
I only find function about RVD in geogram.

**Comment by BrunoLevy** [comment]
Yes it does, 
see [here](https://github.com/BrunoLevy/geogram/wiki/Delaunay3D#weighted-triangulation)
(weighted triangulation is the internal representation for a power diagram).

See also [optimal transport](https://github.com/BrunoLevy/geogram/tree/main/src/lib/exploragram/optimal_transport) for examples of computing a power diagram restricted to a surface or a volume.
