### ISSUE TITLE
Rename Process::current_task

### ISSUE THREAD

**Issue by jdumas** [BrunoLevy/geogram#66]
We've had some issues with [current_task](https://github.com/BrunoLevy/geogram/blob/d9c57b3ea7f7ce16dbb2f558c5700580dbb7b967/src/lib/geogram/basic/progress.h#L176), which conflicts with a [macro](https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/osfmk/kern/task.h#L562) in the macOS SDK... Renaming it to something else should solve this issue.

**Comment by BrunoLevy** [comment]
I'm starting with this one (the easiest one in your list).  
Pushed the fix, waiting for the testsuite to complete...

**Comment by BrunoLevy** [comment]
All lights green for this one.
The other ones will take more time (but I'm working on them), than you very much @jdumas for having taken the time to file them here, it helps a lot !

**Comment by jdumas** [comment]
No worries. Let me know if I can help review some of those changes.
