### ISSUE TITLE
Add option to use OneTBB for multithreading

### ISSUE THREAD

**Issue by jdumas** [BrunoLevy/geogram#67]
It'd be great to be able to use OneTBB as the multithreading backend. Using the same scheduler in a larger app really helps avoiding oversubscription in general. When I was at nTopology I did some work in [this direction](https://github.com/nTopology/geogram/commit/1c12a8e591fdf5ad7ce6f6e680e57649cddb6e86#diff-9b78d6ab542063489c880f9d1d0a3d2ecfeca1396acda92d63f4a3a7f82cfbaaR716-R814) in our geogram fork at the time (using an older TBB version). Maybe this can provide some inspiration. One important change is that TBB's spinlock cannot be initialized with an assignment constructor (`foo = x` syntax), so this requires a few extra changes in the rest of Geogram.

**Comment by BrunoLevy** [comment]
I have in mind two things:
- for spinlocks, replace them with std::atomic. Do you have an experience with it ? I don't know whether it is efficiently implemented in the compilers (I'll take a look at the generated asm when I have time)
- geogram's thread manager is abstracted, so it would be easy to have a OneTBB implementation

**Comment by jdumas** [comment]
I think `std::atomic` should be generally faster than any mutex implementation, but it really depends on the usage, so one would need to profile to be sure. TBB has its own `spin_mutex` implementation, among many other flavors. They have [a page](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Mutex_Flavors.html) that explains the different flavors and how they scale wrt to each others. I am not familiar enough with them to know which one would be more suited for Geogram.
