### ISSUE TITLE
Artifacts created during hole filling

### ISSUE THREAD

**Issue by sterlinglaird** [BrunoLevy/geogram#72]
Hi Bruno, thanks for making such a great library public!

I'm using geogram to (among other things) fill holes in meshes created by my application. I noticed some artifacts that the hole-filling algorithm creates due to the removal of "bridge facets".

I see that the first step in hole filling is to detect and remove these bridge facets before identifying and filling holes. However if the bridge facets that we removed are part of a hole that is too big to be filled, these new holes caused by removing these facets will remain in the final mesh.

I tested commenting out the line that removed bridges during hole-filling and the result seemed fine - no artifacts in the final mesh. It's not clear to me why bridge facets need to be removed in the first place. Is there some reasoning behind this, or could you could provide a link to literature that justifies it/outlines the algorithms used? Otherwise it seems to me like keeping these bridge facets in the mesh is ok.

A candidate hole to be filled
![candidate_hole](https://user-images.githubusercontent.com/13267819/222577480-3062f98d-f28d-476d-8356-cf908cb9b1cc.png)

The hole after bridge removal but skipping actual hole filling. Note the removed "bridge" facets
![after_bridge_removal](https://user-images.githubusercontent.com/13267819/222577523-d46b2d1e-615c-49ff-ac8a-2db1fb85f997.png)

**Comment by BrunoLevy** [comment]
Thank you very much for this PR. I confirm I can reproduce the problem with a simple mesh. Yes, these are false positives for my "bridge" test. I am investigating...

**Comment by BrunoLevy** [comment]
For now I've deactivated "bridge removal" (that is bugged).
