### ISSUE TITLE
How to download historical version

### ISSUE THREAD

**Issue by zhangjiangzhao123** [BrunoLevy/geogram#87]
I am currently compiling a project that uses version 1.5.1 of geogram, so I would like to ask where I can download this version. This is very useful for me because I encountered some errors when trying to use version 1.8.2, which I believe is due to version issues.

**Comment by BrunoLevy** [comment]
Did not find an archive for 1.5.1 (too old), sorry.
Try with latest version and tell us what you get.

**Comment by BrunoLevy** [comment]
Note: you may restore an older version using the [AliceVision](https://github.com/alicevision/geogram) git mirror, that has older version (unsure it goes down to 1.5.1 but worth trying)
