### ISSUE TITLE
problem of delaunay 

### ISSUE THREAD

**Issue by tyc1998** [BrunoLevy/geogram#9]
I'm having issues with GEO::delaunay, the resulting mesh is of poor quality, even -1 in the cell_to_v array. I have read your demo carefully and found no problem with my code usage, I hope to get your help, best wishes!
Code is as follows:

        GEO::CmdLine::import_arg_group("standard");
        GEO::CmdLine::import_arg_group("pre");
        GEO::CmdLine::import_arg_group("algo");

        GEO::Delaunay::initialize();
		GEO::Delaunay_var T = GEO::Delaunay::create(3, "BDEL");
        //T->set_reorder(true);
		//T->set_thread_safe(true);
		T->set_keeps_infinite(true);
		T->set_vertices(vd_.size() / 3, vd_.data());

		std::vector<Vector4i> indice;
		indice.resize(T->nb_cells());
		const auto& tet2v = T->cell_to_v();
		for (int i = 0; i < indice.size(); ++i) {
			for (int j = 0; j < 4; ++j) {
				indice[i][j] = T->cell_vertex(i, j);
			}
		}

**Comment by BrunoLevy** [comment]
Since you called `T->set_keep_infinite(true)`, it creates "infinite" tetrahedra (that connect three vertices of the convex hull and the infinite vertex, of index -1). If you do not want them, simply remove the line with `T->set_keep_infinite(true)`. What do you mean by "the resulting mesh is of poor quality" ? Delaunay triangulation is a well-defined mathematical concept: there is (nearly) a unique Delaunay triangulation for a given set of points. Maybe what you need is a 3D mesher, that decices where to put the points. For that, see the functions in [mesh_tetrahedralize.h](https://brunolevy.github.io/geogram/mesh__tetrahedralize_8h.html) (that use tetgen).

**Comment by tyc1998** [comment]
> 由于您调用`T->set_keep_infinite(true)`，它会创建“无限”四面体（连接凸包的三个顶点和索引为 -1 的无限顶点）。如果您不想要它们，只需删除带有`T->set_keep_infinite(true)`. “生成的网格质量差”是什么意思？Delaunay 三角剖分是一个定义明确的数学概念：对于给定的一组点，（几乎）存在唯一的 Delaunay 三角剖分。也许您需要的是一个 3D 网格划分器，它决定了在哪里放置点。为此，请参阅 mesh_tetrahedralize.h 中的函数[（](https://brunolevy.github.io/geogram/mesh__tetrahedralize_8h.html)使用 tetgen）。

I have found the problem, your code is fine, no problem. It is the problem of my input, my input is not filled with a convex hull due to floating point precision issues, and your code should be a delaunay tetrahedron based on the strictly exact convex hull of the input points. So it was different from what I expected. 
![image](https://user-images.githubusercontent.com/31647878/173292838-f0264b65-981b-402e-997e-a90fe827c9c5.png)
![image](https://user-images.githubusercontent.com/31647878/173293003-b4c153d9-3c2a-4628-947d-39194fa675fc.png)


As shown above, I don't want the lowermost layer of low quality tetrahedral meshes in the output, can you provide a solution. thank you for your reply

**Comment by tyc1998** [comment]
> Since you called `T->set_keep_infinite(true)`, it creates "infinite" tetrahedra (that connect three vertices of the convex hull and the infinite vertex, of index -1). If you do not want them, simply remove the line with `T->set_keep_infinite(true)`. What do you mean by "the resulting mesh is of poor quality" ? Delaunay triangulation is a well-defined mathematical concept: there is (nearly) a unique Delaunay triangulation for a given set of points. Maybe what you need is a 3D mesher, that decices where to put the points. For that, see the functions in [mesh_tetrahedralize.h](https://brunolevy.github.io/geogram/mesh__tetrahedralize_8h.html) (that use tetgen).

I have found the problem, your code is fine, no problem. It is the problem of my input, my input is not filled with a convex hull due to floating point precision issues, and your code should be a delaunay tetrahedron based on the strictly exact convex hull of the input points. So it was different from what I expected.
![image](https://user-images.githubusercontent.com/31647878/173293171-4c7b3761-fa7e-4bc5-bd24-a4046d26a229.png)
![image](https://user-images.githubusercontent.com/31647878/173293197-f4622529-d551-4446-9c2b-24153f79ed56.png)


As shown above, I don't want the lowermost layer of low quality tetrahedral meshes in the output, can you provide a solution. thank you for your reply

**Comment by BrunoLevy** [comment]
Received a DM indicating that the problem was in the input pointset, not in the code, so I'm closing this issue.
