### ISSUE TITLE
Getting the error `o-[Environment ] Error: No such variable: algo:nn_search`

### ISSUE THREAD

**Issue by aditya-c2512** [BrunoLevy/geogram#91]
I am getting the above error log when I try to run the below code:
```
...
points.copy(mesh, false, GEO::MESH_VERTICES);
GEO::Co3Ne_compute_normals(points, 30, true);
GEO::PoissonReconstruction poisson;
...
```
I know it is due to the `Co3Ne_compute_normals` function but how do I fix it?

**Comment by BrunoLevy** [comment]
You need to initialize Geogram libraries, see the examples in `src/examples`
In particuliar, you need to call
```
  GEO::initialize();
```
and to import the command line arguments, using
```
 GEO::CmdLine::import_arg_group("standard");
 GEO::CmdLine::import_arg_group("algo");
```
