### ISSUE TITLE
configure.bat dosen't work

### ISSUE THREAD

**Issue by yyysuki** [BrunoLevy/geogram#93]
I copy the code via download ZIP. Double click the configure.bat but nothing happen(vs version: 2022 Community)

**Comment by yyysuki** [comment]
I see，the cmake path is different.

**Comment by BrunoLevy** [comment]
Does it work now ?

**Comment by yyysuki** [comment]
yes，it works now！thx！ Sent from Mail MasterOn 07/27/2023 21:09, Bruno Levy wrote: 
Does it work now ?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/BrunoLevy/geogram/issues/93#issuecomment-1653596731",
"url": "https://github.com/BrunoLevy/geogram/issues/93#issuecomment-1653596731",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BrunoLevy** [comment]
Thanks ! 
- I'm adding a note in the doc: "make sure that CMake is declared in your path"
- I'm closing the issue
Best,
-- Bruno
